name: Have Fun
description: A blog about having fun solving problems

url: http://blog.hornmicro.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 10

navigation:
 - title: Home
   url: index.html
 - title: About
   url: about.html
 - title: Contact
   url: contact.html